name: CI

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Instalar dependencias
        run: npm install

      - name: Ejecutar ESLint
        run: npm run lint

      - name: Ejecutar tests
        run: npm test

      - name: Build de Docker
        run: docker build -t reto-api-docker-ci .

      - name: Escaneo con Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: reto-api-docker-ci
          format: table
          exit-code: 1
          ignore-unfixed: true
