name: CI/CD con Serveo

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install
      - name: Ejecutar ESLint
        run: npx eslint .

  test:
    needs: eslint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install

      - name: Ejecutar tests con cobertura
        run: npx jest --coverage    

      - name: Generar resumen para PR
        if: github.event_name == 'pull_request'
        run: npx jest --coverage --coverageReporters=text-summary > coverage-summary.txt

      - name: Comentar cobertura en PR
        if: github.event_name == 'pull_request'
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          path: coverage-summary.txt

  docker-validation:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Instalar jq
        run: sudo apt-get install -y jq

      - uses: docker/setup-buildx-action@v3

      - name: Construir imagen Docker
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/reto-practico-3:latest .

      - name: Instalar Trivy
        run: curl -sSL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh
     
      - name: Ejecutar escaneo de seguridad (Trivy)
        run: |
          /usr/local/bin/trivy image --severity HIGH,CRITICAL --exit-code 1 --format json --output trivy-report.json ${{ secrets.DOCKER_USERNAME }}/reto-practico-3:latest
     
      - name: Generar resumen Trivy para PR
        if: github.event_name == 'pull_request'
        run: |
          cat trivy-report.json | jq '.Results[]?.Vulnerabilities? // [] | map("* \(.VulnerabilityID) [\(.PkgName)] - \(.Severity): \(.Title)") | join("\n")' -r > trivy-summary.txt
          echo -e "\n_⚠️ Vulnerabilidades encontradas por Trivy (HIGH/CRITICAL)._ Revisa antes de hacer merge.\n" >> trivy-summary.txt

      - name: Comentar vulnerabilidades en PR
        if: github.event_name == 'pull_request'
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          path: trivy-summary.txt

  build-and-deploy:
    needs: docker-validation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Autenticarse en Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Construir y subir imagen
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/reto-practico-3:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/reto-practico-3:latest

      - name: Hacer deploy vía Serveo
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          password: ${{ secrets.DEPLOY_PASSWORD }}
          port: ${{ secrets.DEPLOY_PORT }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/reto-practico-3:latest
            docker rm -f reto-practico-3 || true
            docker run -d --name reto-practico-3 -p 3000:3000 ${{ secrets.DOCKER_USERNAME }}/reto-practico-3:latest